### ISSUE TITLE
potential bug in pytorch cuda

### ISSUE THREAD

**Issue by ngam** [conda-forge/pytorch-cpu-feedstock#147] opened 2022-11-14 16:25 UTC
> So, as a first swipe, we will need to make the naming conventions work together.

Ah I see, I knew it was some issue with the naming. All those curly bracket substitutions are confusing :sweat_smile:

> I would say, the better solution is to stick with everything from conda-forge and we can get whatever you need from the pytorch channel working correctly here in conda-forge (PRs welcome, of course)

Agree, and I fully support not mixing channels if possible. It's just that I've been getting some annoying warnings like `UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`, and I usually found in the past that `pytorch::pytorch` works better, though `conda-forge::pytorch` has been getting much better I must say!

_Originally posted by @weiji14 in https://github.com/conda-forge/mmcv-recipe-feedstock/pull/16#discussion_r1021772402_

**Comment by weiji14** [comment] 2022-11-14 21:06
It's actually for the UserWarning. I think it's because I was mixing `pytorch` from 'conda-forge' channel with `torchvision` from 'pytorch' channel. Here's a reproducible example:

```bash
mamba create --name temp python=3.9 conda-forge::pytorch=1.12 conda-forge::mmcv-full=1.7.0 conda-forge::mmdet=2.25.3 pytorch::torchvision=0.13.1=py39_cu11conda-forge::torchvision=0.13.0
mamba activate temp
python
```
Then in the Python interpreter, run
```python
import mmdet.models
```
which should give
```python-traceback
/home/username/mambaforge/envs/temp/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/username/mambaforge/envs/temp/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
```

should be solved by not mixing channels (i.e. getting both `pytorch` and `torchvision` from 'conda-forge' only, or from 'pytorch' only), which I hope https://github.com/conda-forge/mmcv-recipe-feedstock/pull/16 will help with. Feel free to close this issue as wontfix.

**Comment by hmaarrfk** [comment] 2022-11-15 03:57
There is no guaranteed compatibility between pytorch channel and conda-forge.

I only tried to keep the naming consistent so that people could do a full switch over.

Why don't you want to use torchvision from conda-forge?

https://github.com/conda-forge/torchvision-feedstock

**Comment by weiji14** [comment] 2022-11-15 15:58
Thanks folks, I really appreciate all the work that's gone into the conda-forge pytorch ecosystem. Just for context, the issues here were due to me updating some dependencies for a project that started late 2021 that had the 'pytorch' channel pinned higher than 'conda-forge', so the solver was mixing `pytorch::torchvision` with `conda-forge::pytorch` and that was causing those warnings to pop up. Back then, my experience was that the 'pytorch' channel was more up to date on versions (especially with the cuda stuff), hence the channel mixing.

However, I have been keeping watch on the conda-forge packaging, especially on the Pangeo side, and knew that the compatibilities were being worked on. I guess I just didn't realize things were so good already on conda-forge :laughing:. In fact, I just tried dropping the 'pytorch' channel and re-installing everything from conda-forge, and it works perfectly fine :partying_face:

> PRs, etc. are always welcome and please let us know of any issues so that we can fix them. For example, if you have a parallel workflow with conda-forge-only packages, could you let us know any shortcomings (compared to the one from pytorch channel)? Then, we will look into fixing them

Yes, I'll definitely submit bug reports if anything pops up. Sorry again for the noise, I was mostly thinking out loud while trying to update a bunch of dependencies, and forgot to revisit the rule of 'no channel mixing whenever possible'. Please feel free to close this issue.

**Closed as completed** 2022-11-15 17:41 UTC

**Comment by hmaarrfk** [comment] 2022-11-16 03:04
The migration has not been easy that is for sure.
